apiVersion: 1

datasources:
  - name: Elasticsearch-WebApp
    uid: Elasticsearch-WebApp
    type: elasticsearch
    access: proxy
    url: http://localhost:9200
    isDefault: true
    jsonData:
      index: webapp-logs-*
      timeField: "timestamp"
      interval: "1m"
      esVersion: 8.0.0
      includeFrozen: false

  - name: Elasticsearch-WebML
    uid: Elasticsearch-WebML
    type: elasticsearch
    access: proxy
    url: http://localhost:9200
    isDefault: false
    jsonData:
      index: web-ml-anomalies-*
      timeField: "timestamp"
      interval: "1m"
      esVersion: 8.0.0
      includeFrozen: false
